name: MacOS VoiceOver for macOS-15

on: 
  workflow_dispatch:

jobs:
  start-voiceover-and-move-right:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-15]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Older Path
        run: |
          ls -l ~/Library/Preferences/com.apple.VoiceOver4/ || echo "Directory not found"

      - name: move to new sandboxed path
        run: |
         mkdir -p ~/Library/Group\ Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4 && \
         mv -v ~/Library/Preferences/com.apple.VoiceOver4/default.plist ~/Library/Group\ Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4/


      - name: Disable VoiceOver Splash Screen
        run: |
          defaults write com.apple.VoiceOverTraining doNotShowSplashScreen -bool true
          echo "Splash screen disabled."

      - name: Start VoiceOver
        run: |
          /System/Library/CoreServices/VoiceOver.app/Contents/MacOS/VoiceOverStarter &
          sleep 2
          ps aux | grep "[V]oiceOver" || echo "VoiceOver process not found"

      - name: Check if VoiceOver is Running
        run: |
          /usr/bin/osascript voiceOverRunning.applescript || echo "AppleScript check failed"

      - name: Activate VoiceOver
        run: |
          until /usr/bin/osascript voiceOverActivate.applescript; do
            echo "Waiting for VoiceOver activation..."
            sleep 1
          done
          echo "VoiceOver activated."

      - name: Perform VoiceOver Actions
        run: |
          until /usr/bin/osascript voiceOverPerform.applescript; do
            echo "Failed to perform AppleScript, retrying..."
            sleep 1
          done
          echo "VoiceOver interaction complete."

      - name: Terminate VoiceOver
        run: |
          pid=$(pgrep -f "VoiceOver.app/Contents/MacOS/VoiceOver")
          if [ -n "$pid" ]; then
            echo "Terminating VoiceOver (PID: $pid)"
            kill -15 "$pid"
          else
            echo "VoiceOver process not found."
          fi
